if (self.CavalryLogger) { CavalryLogger.start_js_script(document.currentScript); }/*FB_PKG_DELIM*/

__d("Base64",[],(function(a,b,c,d,e,f){var g="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";function h(a){a=a.charCodeAt(0)<<16|a.charCodeAt(1)<<8|a.charCodeAt(2);return String.fromCharCode(g.charCodeAt(a>>>18),g.charCodeAt(a>>>12&63),g.charCodeAt(a>>>6&63),g.charCodeAt(a&63))}var i=">___?456789:;<=_______\0\x01\x02\x03\x04\x05\x06\x07\b\t\n\v\f\r\x0e\x0f\x10\x11\x12\x13\x14\x15\x16\x17\x18\x19______\x1a\x1b\x1c\x1d\x1e\x1f !\"#$%&'()*+,-./0123";function j(a){a=i.charCodeAt(a.charCodeAt(0)-43)<<18|i.charCodeAt(a.charCodeAt(1)-43)<<12|i.charCodeAt(a.charCodeAt(2)-43)<<6|i.charCodeAt(a.charCodeAt(3)-43);return String.fromCharCode(a>>>16,a>>>8&255,a&255)}var k={encode:function(a){a=unescape(encodeURI(a));var b=(a.length+2)%3;a=(a+"\0\0".slice(b)).replace(/[\s\S]{3}/g,h);return a.slice(0,a.length+b-2)+"==".slice(b)},decode:function(a){a=a.replace(/[^A-Za-z0-9+\/]/g,"");var b=a.length+3&3;a=(a+"AAA".slice(b)).replace(/..../g,j);a=a.slice(0,a.length+b-3);try{return decodeURIComponent(escape(a))}catch(a){throw new Error("Not valid UTF-8")}},encodeObject:function(a){return k.encode(JSON.stringify(a))},decodeObject:function(a){return JSON.parse(k.decode(a))},encodeNums:function(a){return String.fromCharCode.apply(String,a.map(function(a){return g.charCodeAt((a|-(a>63?1:0))&-(a>0?1:0)&63)}))}};a=k;f["default"]=a}),66);
__d("Deferred",["Promise"],(function(a,b,c,d,e,f){"use strict";b("Promise").resolve();a=function(){function a(a){var c=this;a=a||b("Promise");this.$1=!1;this.$2=new a(function(a,b){c.$3=a,c.$4=b})}var c=a.prototype;c.getPromise=function(){return this.$2};c.resolve=function(a){this.$1=!0,this.$3(a)};c.reject=function(a){this.$1=!0,this.$4(a)};c.isSettled=function(){return this.$1};return a}();f["default"]=a}),66);/*FB_PKG_DELIM*/
__d("LSVerifyContactRowExists",["LSIssueNewTask"],(function(a,b,c,d,e,f){function a(){var a=arguments,c=a[a.length-1];c.n;var d=[],e=[],f;return c.seq([function(e){return c.ftr(c.db.table(7).fetch([[[a[0]]]]),function(b){return c.i64.eq(b.id,a[0])&&c.i64.eq([0,1],[0,1])}).next().then(function(e){var g=e.done;e.value;return g?c.seq([function(b){return d[0]=a[3]==null?"":a[3],c.fe(c.ftr(c.db.table(7).fetch([[[a[0]]]]),function(b){return c.i64.eq(b.id,a[0])&&c.i64.eq([0,1],[0,1])&&c.i64.lt(b.authorityLevel,a[14])}),function(a){return a["delete"]()})},function(b){return c.db.table(7).add({id:a[0],profilePictureUrl:a[2]==null?"":a[2],profilePictureFallbackUrl:a[5],name:d[0],secondaryName:a[20],normalizedNameForSearch:d[0],isMemorialized:a[9],blockedByViewerStatus:a[11],canViewerMessage:a[12],profilePictureLargeUrl:"",isMessengerUser:!0,rank:0,contactType:a[4],contactTypeExact:[0,0],requiresMultiway:!1,authorityLevel:a[14],workForeignEntityType:[0,0],capabilities:a[15],capabilities2:a[16],contactViewerRelationship:a[19],gender:a[18]})},function(e){return d[1]=new c.Map(),d[1].set("contact_id",a[0]),d[2]=c.toJSON(d[1]),c.sp(b("LSIssueNewTask"),"cpq_v2",[0,207],d[2],f,f,[0,0],[0,0],f,f,[0,0])}]):0})},function(a){return c.resolve(e)}])}e.exports=a}),null);
__d("LSUpdateLastSyncCompletedTimestampMsToNow",[],(function(a,b,c,d,e,f){function a(){var a=arguments,b=a[a.length-1];b.n;var c=[];return b.seq([function(c){return b.fe(b.db.table(1).fetch([[[a[0]]]]),function(a){var c=a.update;a.item;return c({lastSyncCompletedTimestampMs:b.i64.of_float(Date.now())})})},function(a){return b.resolve(c)}])}e.exports=a}),null);
__d("LSTransaction.bs",[],(function(a,b,c,d,e,f){"use strict";function a(a,b,c){return a.runInTransaction(b,function(){switch(c){case"readOnly":return"readonly";case"readWrite":return"readwrite"}}())}f.run=a}),null);/*FB_PKG_DELIM*/
__d("getCometBadgeColorStyle",["unrecoverableViolation"],(function(a,b,c,d,e,f,g){"use strict";var h={blue:{backgroundColor:"is6700om"},darkGray:{backgroundColor:"mvk259uv"},gray:{backgroundColor:"p2o8ms9n"},green:{backgroundColor:"jllm4f4h"},lightBlue:{backgroundColor:"b8zhkkm9"},red:{backgroundColor:"gky8063y"},yellow:{backgroundColor:"tutozmqo"}};function a(a){switch(a){case"blue":return h.blue;case"gray":return h.gray;case"darkGray":return h.darkGray;case"green":return h.green;case"lightBlue":return h.lightBlue;case"red":return h.red;case"yellow":return h.yellow;default:a;throw c("unrecoverableViolation")(" Invalid color in getCometBadgeColorStyle","comet_ui")}}g["default"]=a}),98);
__d("MWLSSchemaEphemeral.bs",["LSDefaultSyncGroups","LSJSInMemoryStorage.bs","LSMetadata","LSTransaction.bs","Promise"],(function(a,b,c,d,e,f){"use strict";function a(a){return b("Promise").resolve(b("LSJSInMemoryStorage.bs").make(b("LSMetadata").metadata)).then(function(a){return b("LSTransaction.bs").run(a,function(a){return b("LSDefaultSyncGroups").seedDb(a,b("LSDefaultSyncGroups").defaultSyncGroups)},"readWrite").then(function(b){return a})})}f.createDB=a}),null);
__d("react-relay/relay-hooks/useClientQuery",["react-relay/relay-hooks/useLazyLoadQuery"],(function(a,b,c,d,e,f){"use strict";function a(a,c,d){a=a;return b("react-relay/relay-hooks/useLazyLoadQuery")(a,c,babelHelpers["extends"]({},d,{fetchPolicy:"store-only"}))}e.exports=a}),null);/*FB_PKG_DELIM*/
__d("LSRemoveTask",[],(function(a,b,c,d,e,f){function a(){var a=arguments,b=a[a.length-1];b.n;var c=[];return b.seq([function(c){return b.db.table(2).fetch([[[a[0]]]]).next().then(function(c,d){var e=c.done;c=c.value;return e?0:(d=c.item,b.fe(b.db.table(2).fetch([[[d.queueName,{lte:a[0]}]],"queueNameTaskId"]),function(a){return a["delete"]()}))})},function(a){return b.resolve(c)}])}e.exports=a}),null);
__d("LSTaskExists",[],(function(a,b,c,d,e,f){function a(){var a=arguments,b=a[a.length-1];b.n;var c=[],d=[];return b.seq([function(e){return b.seq([function(d){return b.db.table(2).fetch([[[a[0]]]]).next().then(function(a,b){b=a.done;a=a.value;return b?c[0]=!1:(a.item,c[0]=!0)})},function(a){return d[0]=c[0]}])},function(a){return b.resolve(d)}])}e.exports=a}),null);